### PR TITLE
WIP: Upgrade bitcoin

### PR DESCRIPTION
**Pull request by tcharding**
Here's a rough look at whats needed to upgrade to the latest `rust-bitcoin v0.31.1`.

Note, all the base64 stuff needs checking, I don't know what ohttp is, I just swung my axe around wildly.

I used a local version of `bip21`, it has the bitcoin upgrade already on master.

Fix: #124

### CODE REVIEW

**Comment by tcharding** [comment]
The lock file makes the diff numbers look way worse than they are :)

**Review by DanGould — COMMENTED** [review]
Thanks for your contribution Tobin!

I found 2 concerns

1: I believe we have to use Base64 url encoding in the bip21 uris, so I'm not sure BASE64_STANDARD is suitable in those places.
2: I left some hints as to the `ohttp` details. We need to pass around [OHTTP Key Configuration](https://ietf-wg-ohai.github.io/oblivious-http/draft-ietf-ohai-ohttp.html#name-key-configuration-media-typ) details since the ip-protecting authenticated encryption in payjoin v2 uses keys shared in the URI instead of TLS/WebPKI.

**Comment by tcharding** [comment]
Thanks for the explanations man, I'll give this a bit more brain space.

**Comment by tcharding** [comment]
I'm not going to get to this any time soon man, way too much todo in `rust-bitcoin`.

**Pull request closed without merging**
