### PR TITLE
payjoin-cli: add example config

### PR DESCRIPTION
**Pull request by thebrandonlucas**
Adds an example config with each config option and an explanation to improve UX of using payjoin-cli and to provide a reference they can use. This can probably be improved by adding examples but I think this is a good start

### CODE REVIEW

**Comment by DanGould** [comment]
Great idea. This seems like more of a template than an example which is still viable. When I think example, I think filled out. A template could have unset config lines commented, and notes perhaps double / triple commented. Also a bit stsrange that `bitcoind_rpcuser=` is the only commented parameter.

I also think it's natural to want space after each section. hard to tell them apart right now, where there's note, then space, then the config parameter, but no space thereafter. 

I suggest renaming it `template.config.toml` if it's not going to be filled out and commenting the lines out as described.

**Review by DanGould — CHANGES_REQUESTED** [review]
Great idea. This seems like more of a template than an example which is still viable. When I think example, I think filled out. A template could have unset config lines commented, and notes perhaps double / triple commented. Also a bit stsrange that bitcoind_rpcuser= is the only commented parameter.

I also think it's natural to want space after each section. hard to tell them apart right now, where there's note, then space, then the config parameter, but no space thereafter.

I suggest renaming it template.config.toml if it's not going to be filled out and commenting the lines out as described.

**Comment by thebrandonlucas** [comment]
> When I think example, I think filled out.

We can consider filling them out for sure. You mentioned this elsewhere, but it's hard to know what to put in there (even with an explanation without an example. I'll fill them out with the defaults we know of (i.e. `pj_endpoint="https://payjo.in"`, etc.), and keep the descriptions for maximum helpfulness/clarity.

**Comment by thebrandonlucas** [comment]
@DanGould Updated to be more readable and filled out examples for each with the defaults we are providing in tutorials, and hopefully sane defaults otherwise

**Review by DanGould — APPROVED** [review]
This turned out super nice. Thanks for your patience getting this review.

Do you see this as a piece of evolving documentation from which downstream users might configure their CLI? If so, perhaps it should be accessible from the README.

**Comment by thebrandonlucas** [comment]
Yes, once we smooth over some more of the UX issues with `payjoin-cli` to make it a bit more intuitive, perhaps we can do a few README overhauls.

**Pull request merged**
