### PR TITLE
Add example and remove old docs

### PR DESCRIPTION
**Pull request by jbesraa**
#137 

- [ ] remove logs from `receive` module
- [ ] remove logs from `send` module
- [ ] add full example to examples folder

example is implemented with `axum` and `bitcoincore_rpc`

### CODE REVIEW

**Comment by DanGould** [comment]
we could also take the mutiny route where  we load a bdk wallet with in-memory database and point them to a faucet

**Comment by jbesraa** [comment]
> we could also take the mutiny route where we load a bdk wallet with in-memory database and point them to a faucet

Do you have a link please?

**Comment by DanGould** [comment]
if you run this it'll connect to their signet electrum server https://github.com/mutinywallet/mutiny-node and anyone can use their faucet https://faucet.mutinynet.com/

**Comment by DanGould** [comment]
This pr should not depend on PjUriBuilder. That should keep us from being blocked on that issue and allow us to triage this independently

**Comment by DanGould** [comment]
Is it possible to split the docs removal? It's easier to review PRs in isolation, and I'm not sure if this is doing two things (as the title implies) or many, as the commit log seems to imply

**Comment by jbesraa** [comment]
closing in favor of #179 and #180

**Pull request closed without merging**
