### PR TITLE
Rexport base64 as a feature from bitcoin crate

### LINKED ISSUE #30: Pack base64 as a feature
right now you need an external base64 dep, either on its own or typically exported from bitcoin. Since we already use it in the lib we could re-export it or make a helper to get PSBTs in base64 for transit.

### PR DESCRIPTION
**Pull request by jbesraa**
resolves #30

### CODE REVIEW

**Comment by jbesraa** [comment]
@DanGould 
Tried to pint rustls to 0.21.1 but apparently bitcoind is using a package that requires 0.21.6
bitcoind is only used for testing i think.. how to continue with this? 


```
 error: failed to select a version for the requirement `rustls = "^0.21.6"`
candidate versions found which didn't match: 0.21.1
location searched: crates.io index
required by package `minreq v2.9.0`
    ... which satisfies dependency `minreq = "^2.6.0"` (locked to 2.9.0) of package `bitcoind v0.31.1`
    ... which satisfies dependency `bitcoind = "^0.31.1"` (locked to 0.31.1) of package `payjoin v0.9.0 (/home/runner/work/rust-payjoin/rust-payjoin/payjoin)`
```

**Comment by DanGould** [comment]
@notmandatory Would you consider this [dev-dependencies] failure an actual failure to comply with msrv? The package builds on 1.57.0 but the tests require 1.63 or newer.

**Comment by notmandatory** [comment]
> @notmandatory Would you consider this [dev-dependencies] failure an actual failure to comply with msrv? The package builds on 1.57.0 but the tests require 1.63 or newer.

Strictly speaking it's enough to build with the MSRV in CI since that also verifies MSRV version pinning `cargo update` commands are correct. For BDK projects we also have CI run all our tests with stable and MSRV versions of rust because it hasn't caused any problems, but if it does we'd probably disable the re-testing for MSRV too.

**Comment by notmandatory** [comment]
Try adding this line to the `rust.yml` CI for testing with 1.57.0 (and update the corresponding section of the README):

```
cargo update -p minreq --precise 2.8.0
```

This should fix the CI. Looks like latest `bitcoind` is using 2.9.0 which brings in some TLS code that's not happy with 1.57.

**Comment by jbesraa** [comment]
thank you @notmandatory

**Comment by DanGould** [comment]
Beautiful PR @jbesraa with well ordered, named, and separated commits. Efforts making big progress.

@notmandatory thanks a ton for the quick help. How did you identify the minreq version to be pinned? Just intuit that that's where the tls problem came from and check crates.io for recent changes?

**Comment by notmandatory** [comment]
> Beautiful PR @jbesraa with well ordered, named, and separated commits. Efforts making big progress.
> 
> @notmandatory thanks a ton for the quick help. How did you identify the minreq version to be pinned? Just intuit that that's where the tls problem came from and check crates.io for recent changes?

My go-to rust command is `cargo tree -i <what ever broke ci>` then go look things up on crates.io to see what their MSRVs are, then rerun the tests with 1.57 until it works. So a little science and a little trial and error.

**Pull request merged**
