### PR TITLE
Add code coverage to CI with Coveralls integration

### PR DESCRIPTION
**Pull request by spacebear21**
This brings the github actions up-to-date with latest versions and adds more descriptive names to the workflow steps.

It also swaps the ordering of `rust-cache` and the rust toolchain installation steps so that cache actually works.

Finally, a new CI step adds code coverage measurements using `cargo-llvm` and uploads the results to Coveralls.

### CODE REVIEW

**Comment by spacebear21** [comment]
Coverage report for this PR can be found here: https://coveralls.io/jobs/155930549.

**Comment by spacebear21** [comment]
It may be useful to enable coveralls [PR comments](https://docs.coveralls.io/app-notifications#pull-request-comments) if we feel comfortable with giving their bot write access to the repo. FWIW rust-bitcoin does this.

**Review by DanGould — APPROVED** [review]
The only thing this seems to be missing is the edit of the README to say

> - [x] Coverage measurement

Did you check that cache hits are occurring as expected with this new form? I must admit I have never checked before.

**Comment by spacebear21** [comment]
> Did you check that cache hits are occurring as expected with this new form? I must admit I have never checked before.

I did and they do! You can see that it restores the cache in the "Use Cache" step and that the dependencies are fresh instead of re-downloaded/re-compiled: https://github.com/payjoin/rust-payjoin/actions/runs/11791047279/job/32842477162?pr=385.

**Pull request merged**
